/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillSlugRouteImport } from './routes/skill.$slug'
import { Route as PromptSlugRouteImport } from './routes/prompt.$slug'
import { Route as PackSlugRouteImport } from './routes/pack.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AccountDownloadsRouteImport } from './routes/account.downloads'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicPurchaseEmailRouteImport } from './routes/api/public/purchase-email'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillSlugRoute = SkillSlugRouteImport.update({
  id: '/skill/$slug',
  path: '/skill/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptSlugRoute = PromptSlugRouteImport.update({
  id: '/prompt/$slug',
  path: '/prompt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PackSlugRoute = PackSlugRouteImport.update({
  id: '/pack/$slug',
  path: '/pack/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDownloadsRoute = AccountDownloadsRouteImport.update({
  id: '/account/downloads',
  path: '/account/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPurchaseEmailRoute = ApiPublicPurchaseEmailRouteImport.update({
  id: '/api/public/purchase-email',
  path: '/api/public/purchase-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/skills': typeof SkillsRoute
  '/waitlist': typeof WaitlistRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/pack/$slug': typeof PackSlugRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/skill/$slug': typeof SkillSlugRoute
  '/api/public/purchase-email': typeof ApiPublicPurchaseEmailRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/skills': typeof SkillsRoute
  '/waitlist': typeof WaitlistRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/pack/$slug': typeof PackSlugRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/skill/$slug': typeof SkillSlugRoute
  '/api/public/purchase-email': typeof ApiPublicPurchaseEmailRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/skills': typeof SkillsRoute
  '/waitlist': typeof WaitlistRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/pack/$slug': typeof PackSlugRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/skill/$slug': typeof SkillSlugRoute
  '/api/public/purchase-email': typeof ApiPublicPurchaseEmailRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/resources'
    | '/skills'
    | '/waitlist'
    | '/account/downloads'
    | '/checkout/success'
    | '/pack/$slug'
    | '/prompt/$slug'
    | '/skill/$slug'
    | '/api/public/purchase-email'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/resources'
    | '/skills'
    | '/waitlist'
    | '/account/downloads'
    | '/checkout/success'
    | '/pack/$slug'
    | '/prompt/$slug'
    | '/skill/$slug'
    | '/api/public/purchase-email'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/resources'
    | '/skills'
    | '/waitlist'
    | '/account/downloads'
    | '/checkout/success'
    | '/pack/$slug'
    | '/prompt/$slug'
    | '/skill/$slug'
    | '/api/public/purchase-email'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ResourcesRoute: typeof ResourcesRoute
  SkillsRoute: typeof SkillsRoute
  WaitlistRoute: typeof WaitlistRoute
  AccountDownloadsRoute: typeof AccountDownloadsRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  PackSlugRoute: typeof PackSlugRoute
  PromptSlugRoute: typeof PromptSlugRoute
  SkillSlugRoute: typeof SkillSlugRoute
  ApiPublicPurchaseEmailRoute: typeof ApiPublicPurchaseEmailRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$slug': {
      id: '/skill/$slug'
      path: '/skill/$slug'
      fullPath: '/skill/$slug'
      preLoaderRoute: typeof SkillSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/$slug': {
      id: '/prompt/$slug'
      path: '/prompt/$slug'
      fullPath: '/prompt/$slug'
      preLoaderRoute: typeof PromptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack/$slug': {
      id: '/pack/$slug'
      path: '/pack/$slug'
      fullPath: '/pack/$slug'
      preLoaderRoute: typeof PackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/downloads': {
      id: '/account/downloads'
      path: '/account/downloads'
      fullPath: '/account/downloads'
      preLoaderRoute: typeof AccountDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/purchase-email': {
      id: '/api/public/purchase-email'
      path: '/api/public/purchase-email'
      fullPath: '/api/public/purchase-email'
      preLoaderRoute: typeof ApiPublicPurchaseEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ResourcesRoute: ResourcesRoute,
  SkillsRoute: SkillsRoute,
  WaitlistRoute: WaitlistRoute,
  AccountDownloadsRoute: AccountDownloadsRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  PackSlugRoute: PackSlugRoute,
  PromptSlugRoute: PromptSlugRoute,
  SkillSlugRoute: SkillSlugRoute,
  ApiPublicPurchaseEmailRoute: ApiPublicPurchaseEmailRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
